# Generated by Django 5.1.5 on 2025-02-24 11:49

import django.db.models.deletion
import master_widgets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_department_description_employee_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=master_widgets.models.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='org.department', verbose_name='Родительское подразделение'),
        ),
        migrations.AddField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='org.workgroup'),
        ),
    ]
