# Generated by Django 5.1.5 on 2025-02-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_workgroup_alter_department_parent_employee_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workgroup',
            options={'ordering': ('name',), 'verbose_name': 'Рабочая группа', 'verbose_name_plural': 'Рабочие группы'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='org.workgroup', verbose_name='Рабочие группы'),
        ),
    ]
